### ISSUE TITLE
Available for 1.7.x?

### ISSUE THREAD

**Issue by antoine-pous** [NodeBB-Community/nodebb-plugin-custom-pages#54]
Hi!

Is this plugin compatible with breaking changes between 1.6.x and 1.7.x?

**Comment by psychobunny** [comment]
Hello yes. The latest version is certainly compatible with the latest version of NodeBB (1.7.3 as of writing). As for individual versions between 1.6.x and 1.7.x, I can't say for sure, but you'd probably be better off upgrading to latest core anyway. :)
