### ISSUE TITLE
Doesn't work with nodebb v1.7.5

### ISSUE THREAD

**Issue by TLINDEN** [NodeBB-Community/nodebb-plugin-custom-pages#55]
I installed it with npm install and restarted nodebb, activated the plugin, restarted again. The plugin shows up as active, if I go to the plugin page at `/admin/plugins/custom-pages` this appears in the nodebb logs:
```
2018-02-15T10:09:34.056Z [17787] - error: /assets/templates/admin/plugins/custom-pages.js
2018-02-15T10:09:34.056Z [17787] - error: /assets/templates/admin/plugins/custom-pages.js
 Error: ENOENT: no such file or directory, open '/home/curv/nodebb/build/public/templates/admin/plugins/custom-pages.tpl'
 Error: ENOENT: no such file or directory, open '/home/curv/nodebb/build/public/templates/admin/plugins/custom-pages.tpl'
    at Error (native)
    at Error (native)
```
Next I copied `custom-pages.tpl` from the git repo to `build/public/templates/admin/plugins/custom-pages.tpl` and even restarted nodebb.

However, if I now go to the plugin admin page, nothing happens anymore and no error shows in the log.

**Comment by TLINDEN** [comment]
Ok, after shift-reloading the plugin admin page renders, but the "add" button on the bottom right doesn't work, nothing happens, no JS errors are visible in the console.

**Comment by 0312birdzhang** [comment]
Seems conflict with `widgets`, when i removed all widgets it works.
But widgets is indeed.

**Comment by trishla08** [comment]
I am having the same issue. Used npm install, activated the plugin, added the custom-pages.tpl to build/public/templates/admin/plugins/custom-pages.tpl  However, when I visit the plugin from ACP, I get a blank screen with no errors in the log or console.

![image](https://user-images.githubusercontent.com/27439626/46579543-cad58800-ca31-11e8-97b1-3160d7cf43cf.png)

Could someone please help me out? Shift reloading doesn't help. I don't have any active widgets too!

@TLINDEN could you solve it?

**Comment by psychobunny** [comment]
Missed this issue, sorry -- fix for the switch to benchpressjs: https://github.com/NodeBB-Community/nodebb-plugin-custom-pages/commit/1d2558f6e225efbd8cbf9cff0053d22ea0e6b5e8

Plugin has also been updated to 1.10.2 now
