### ISSUE TITLE
Custom page not navigable

### ISSUE THREAD

**Issue by nilsramsperger** [NodeBB-Community/nodebb-plugin-custom-pages#57]
Hello,

today I updated custom-pages from 1.0.0 to 1.0.1 on my NodeBB 1.10.2.
After the update I get a "not found" message, when I try to navigate to a custom page.

I checked the plugin settings. The page is still defined. Under widgets the content is still there.
I deleted the page and deactivated the plugin. Restarted NodeBB, activated the plugin and created the page from scratch. Still the same behaviour.

Do you have an idea how to fix the problem or where to look to narow it down?

Thank you for help
Nils

**Comment by aworobel** [comment]
Hello,

Same problem here and same steps tried.
Nothing in the logs too.

Thanks for help :)
Arnaud.

**Comment by aworobel** [comment]
@nilsramsperger : 
In the meantime, you can downgrade :  npm install nodebb-plugin-custom-pages@1.0.0
Tested and working for me :)

**Comment by Finch29** [comment]
Hello exacly the same problem ... i downgrade and it works but an hot fix should be welcome :)

**Comment by RikoDEV** [comment]
I have the same problem on my forum.

Nodebb: 1.10.2
Node.js: 10.13.0

**Comment by gtfr** [comment]
Same here. When I update to Nodebb 1.10.2, my custom pages are not accessible any more.

**Comment by psychobunny** [comment]
Should be fixed with 1.0.2 of this plugin. Sorry about that!
