### ISSUE TITLE
Is it possible to have custom meta data for custom pages?

### ISSUE THREAD

**Issue by fais3000** [NodeBB-Community/nodebb-plugin-custom-pages#60]
I'm specifically interested in modifying the <head> section of the custom pages created through this plugin.

**Comment by barisusakli** [comment]
Since this plugin renders the page with `res.render` it will cause a `filter:<customTplName>.build` to fire. Which means another plugin can add custom data that can be used inside the widgets.

Example
```
// in a separate plugin
myPluign.filterCustomTplBuild = async (hookData) => {
   hookData.templateData.foo = 1;
};
```

Then inside widget for that custom page you can do

```
foo is {foo}
```
