### ISSUE TITLE
Page not working after update nodebb v1.13.4-0.

### ISSUE THREAD

**Issue by zaasmi** [NodeBB-Community/nodebb-plugin-custom-pages#63]
Please update plugin or solve the issue?

**Comment by barisusakli** [comment]
which version of the plugin?

**Comment by zaasmi** [comment]
> which version of the plugin?
Dear @barisusakli Thank you for replying 
nodebb-plugin-custom-pages v1.2.0

**Comment by barisusakli** [comment]
What version of nodejs are you using? This plugin requires at least nodejs 10.0

**Comment by zaasmi** [comment]
oh that's why we are using NJS v8.16.2.

**Comment by zaasmi** [comment]
Please can you suggest a single command to upgrade NJs without disturbing form.

**Comment by barisusakli** [comment]
On ubuntu 

```
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Just google how to upgrade nodejs

**Comment by zaasmi** [comment]
Thanks Woking after Update
