### ISSUE TITLE
custom-pages plugin page currently unresponsive on NodeBB v1.19.3.

### ISSUE THREAD

**Issue by algebuckina** [NodeBB-Community/nodebb-plugin-custom-pages#67]
After updating from 1.18 to 1.19, the ability to edit and create pages has become non functional.

**Comment by barisusakli** [comment]
Which version of the plugin are you using?

**Comment by algebuckina** [comment]
1.3.2 which is apparently latest.

**Comment by barisusakli** [comment]
Please try with 1.3.3 and let me know if it works

**Comment by algebuckina** [comment]
Fix worked. Thankyou.
