### ISSUE TITLE
Not Working w/ NodeBB 2.6.0

### ISSUE THREAD

**Issue by OldManUmby** [NodeBB-Community/nodebb-plugin-custom-pages#69]
Not sure if this plug-in is still in development or supported.

I try to install it on NodeBB 2.6.0, and it seemed to install OK, but times-out when I go to Plugins > Custom Pages.

**Comment by barisusakli** [comment]
@OldManUmby I just tried nodebb-plugin-custom-pages@1.3.4 on nodebb 2.6.0, and it loads fine. 

Which version of the plugin are you using?

**Comment by OldManUmby** [comment]
I didn't look before I uninstalled it, but I installed using ... npm install nodebb-plugin-custom-pages. I will try again and let you know. THX!
